services:
  world:
    image: maple2-world
    ports:
      - "127.0.0.1:20100:20100"
    environment:
      GAME_DB_CONNECTION: "Server=host.docker.internal;Database=game-server;User=root;Password=maplestory"
      DATA_DB_CONNECTION: "Server=host.docker.internal;Database=maple-data;User=root;Password=maplestory"
      CHANNEL_SERVICE: "game"
      LOGIN_IP: "127.0.0.1"
      GAME_IP: "127.0.0.1"

  login:
    image: maple2-login
    depends_on: 
      - world
    ports:
      - "20001:20001"
    links:
      - "world"
    environment:
      GAME_DB_CONNECTION: "Server=host.docker.internal;Database=game-server;User=root;Password=maplestory"
      DATA_DB_CONNECTION: "Server=host.docker.internal;Database=maple-data;User=root;Password=maplestory"
      WORLD_SERVICE: "world"
      LOGIN_IP: "127.0.0.1"

  game:
    image: maple2-game
    depends_on:
      - world
      - login
    ports:
      - "22001:22001"
      - "127.0.0.1:22100:22100"
    environment:
      GAME_DB_CONNECTION: "Server=host.docker.internal;Database=game-server;User=root;Password=maplestory"
      DATA_DB_CONNECTION: "Server=host.docker.internal;Database=maple-data;User=root;Password=maplestory"
      WORLD_SERVICE: "world"
